#!/usr/bin/env sh
set -e
cd -- "$(dirname -- "$0")"
MACHINE="starch"
ARCH_VERSION="20211201.40458"
ARCH_MIRROR="https://mirror.pkgbuild.com"
IMAGE_URL="$ARCH_MIRROR/images/v$ARCH_VERSION/Arch-Linux-x86_64-basic-$ARCH_VERSION.qcow2"

HELP_MESSAGE='starch version 1.0.0

Usage:
  starch [<command>] [args...]

Commands:
  pull     Pull the Arch Linux image used as the container base
  boot     Boot the Starch container
  setup    Perform initial setup of the Starch container
  exec     Execute command within the Starch container
'

if [ "$1" = "help" ] || [ "$1" = "--help" ]; then
    echo "$HELP_MESSAGE"
    exit 0
elif [ "$(id -u)" != "0" ]; then
    echo "Error: Please run this script as root"
    exit 1
fi

copyto() {
    systemd-run --wait --quiet --machine "$MACHINE" rm "$2" || true
    machinectl copy-to "$MACHINE" "$1" "$2"
}

case $1 in
    pull)
        machinectl pull-raw --verify=no "$IMAGE_URL" "$MACHINE"
        ;;
    boot)
        mkdir -p /run/systemd/nspawn/
        cp files/starch.nspawn /run/systemd/nspawn/"$MACHINE".nspawn
        chown root:root /run/systemd/nspawn/"$MACHINE".nspawn
        systemd-run \
            --unit systemd-nspawn-at-"$MACHINE" --property Type=notify \
            systemd-nspawn --machine "$MACHINE" --settings trusted --notify-ready yes
        ;;
    setup)
        copyto files/setup.sh /root/setup.sh
        copyto files/pacman.conf /etc/pacman.conf
        copyto files/sudoers /etc/sudoers
        copyto files/busaccess.service /etc/systemd/system/busaccess.service
        copyto files/runhost.service /etc/systemd/system/runhost.service
        systemd-run --wait --pipe --collect --unit "setup" --machine "$MACHINE" bash /root/setup.sh
        machinectl reboot "$MACHINE"
        ;;
    exec)
        shift
        systemd-run --machine "$MACHINE" --unit "$1" sudo -u starch "$@"
        ;;
    *)
        echo "Error: Unknown command (not one of help, pull, boot, setup or exec)"
        ;;
esac
